In [1]:
import pandas as pd

In [11]:
data = pd.read_csv("VW_VOTARON_2012.csv", encoding = "ISO-8859-1", sep=";")

In [15]:
data.tail(10)

,CEDULA,DV,NACIONALIDAD,PAIS_NACIMIENTO,SEXO,RANGO_EDAD,EDAD,REGION,SUFRAGIO,PARTIDO,COMUNA,CIRCUNSCRIPCION,FECHA_INSCRIPCION,TIPO_INSCRIP,SEMANA,ANO
13404699,0,0,chilena,Chile,masculino,35-39,37,De Coquimbo,no sufragó,SIN PARTIDO,Ovalle,Ovalle,2012,NUEVO,22,1975
13404700,0,0,chilena,Chile,masculino,25-29,26,De Coquimbo,no sufragó,SIN PARTIDO,Ovalle,Ovalle,2012,NUEVO,48,1985
13404701,0,0,chilena,Chile,masculino,18 a 19,18,Arica Y Parinacota,no sufragó,SIN PARTIDO,Arica,San Miguel De Azapa,2012,NUEVO,30,1994
13404702,0,0,chilena,Chile,femenino,20-24,22,Arica Y Parinacota,no sufragó,SIN PARTIDO,Arica,San Miguel De Azapa,2012,NUEVO,5,1990
13404703,0,0,chilena,Chile,masculino,35-39,36,De Coquimbo,no sufragó,SIN PARTIDO,Ovalle,Ovalle,2012,NUEVO,33,1976
13404704,0,0,chilena,Chile,femenino,25-29,26,Arica Y Parinacota,no sufragó,SIN PARTIDO,Arica,San Miguel De Azapa,2012,NUEVO,3,1986
13404705,0,0,chilena,Chile,masculino,18 a 19,18,De Coquimbo,no sufragó,SIN PARTIDO,Ovalle,Ovalle,2012,NUEVO,1,1994
13404706,0,0,chilena,Chile,femenino,20-24,22,De Coquimbo,sufragó,SIN PARTIDO,Ovalle,Ovalle,2012,NUEVO,20,1990
13404707,0,0,chilena,Chile,femenino,20-24,21,De Coquimbo,no sufragó,SIN PARTIDO,Ovalle,Ovalle,2012,NUEVO,10,1991
13404708,0,0,chilena,Chile,masculino,40-44,40,De Coquimbo,no sufragó,SIN PARTIDO,Ovalle,Ovalle,2012,NUEVO,1,1972

In [16]:
data_prueba = data["DV"] == 2

In [17]:
data_prueba.head()

0    False
1    False
2    False
3    False
4    False
Name: DV, dtype: bool

In [18]:
data_filtrada = data[data_prueba]
data_filtrada.head()

Empty DataFrame
Columns: [CEDULA, DV, NACIONALIDAD, PAIS_NACIMIENTO, SEXO, RANGO_EDAD, EDAD, REGION, SUFRAGIO, PARTIDO, COMUNA, CIRCUNSCRIPCION, FECHA_INSCRIPCION, TIPO_INSCRIP, SEMANA, ANO]
Index: []